// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Event struct {
	ID         int64          `json:"id"`
	WorkflowID sql.NullString `json:"workflow_id"`
	TaskID     sql.NullString `json:"task_id"`
	EventType  string         `json:"event_type"`
	EventData  sql.NullString `json:"event_data"`
	CreatedAt  string         `json:"created_at"`
}

type Task struct {
	ID             string         `json:"id"`
	WorkflowID     string         `json:"workflow_id"`
	SequenceNum    int64          `json:"sequence_num"`
	TaskType       string         `json:"task_type"`
	AgentType      string         `json:"agent_type"`
	TargetRepo     string         `json:"target_repo"`
	InputArtifact  string         `json:"input_artifact"`
	OutputArtifact sql.NullString `json:"output_artifact"`
	State          string         `json:"state"`
	ClaimedBy      sql.NullString `json:"claimed_by"`
	ClaimedAt      sql.NullString `json:"claimed_at"`
	Attempts       int64          `json:"attempts"`
	MaxAttempts    int64          `json:"max_attempts"`
	ExitCode       sql.NullInt64  `json:"exit_code"`
	StdoutLog      sql.NullString `json:"stdout_log"`
	StderrLog      sql.NullString `json:"stderr_log"`
	FilesChanged   sql.NullString `json:"files_changed"`
	CreatedAt      string         `json:"created_at"`
	StartedAt      sql.NullString `json:"started_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
	ErrorMessage   sql.NullString `json:"error_message"`
}

type Workflow struct {
	ID              string         `json:"id"`
	OriginalIntent  string         `json:"original_intent"`
	OriginalFile    string         `json:"original_file"`
	CurrentState    string         `json:"current_state"`
	TargetRepo      string         `json:"target_repo"`
	GitBranch       string         `json:"git_branch"`
	MaxDepth        int64          `json:"max_depth"`
	MaxFilesChanged int64          `json:"max_files_changed"`
	MaxDurationMins int64          `json:"max_duration_mins"`
	CurrentDepth    int64          `json:"current_depth"`
	FilesChanged    int64          `json:"files_changed"`
	StartedAt       sql.NullString `json:"started_at"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	CompletedAt     sql.NullString `json:"completed_at"`
	ErrorMessage    sql.NullString `json:"error_message"`
}
