// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClaimTask(ctx context.Context, arg ClaimTaskParams) error
	CompleteTask(ctx context.Context, arg CompleteTaskParams) error
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) error
	FailTask(ctx context.Context, arg FailTaskParams) error
	GetPendingTask(ctx context.Context) (string, error)
	GetTask(ctx context.Context, id string) (Task, error)
	GetWorkflow(ctx context.Context, id string) (Workflow, error)
	ListEvents(ctx context.Context, workflowID sql.NullString) ([]Event, error)
	ReleaseTask(ctx context.Context, id string) error
	RetryTask(ctx context.Context, id string) error
	UpdateWorkflowBudget(ctx context.Context, arg UpdateWorkflowBudgetParams) error
	UpdateWorkflowState(ctx context.Context, arg UpdateWorkflowStateParams) error
}

var _ Querier = (*Queries)(nil)
