// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
)

const claimTask = `-- name: ClaimTask :exec
UPDATE tasks
SET state = 'claimed', claimed_by = ?, claimed_at = datetime('now')
WHERE id = ?
`

type ClaimTaskParams struct {
	ClaimedBy sql.NullString `json:"claimed_by"`
	ID        string         `json:"id"`
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) error {
	_, err := q.db.ExecContext(ctx, claimTask, arg.ClaimedBy, arg.ID)
	return err
}

const completeTask = `-- name: CompleteTask :exec
UPDATE tasks
SET state = 'completed',
    exit_code = ?,
    stdout_log = ?,
    stderr_log = ?,
    files_changed = ?,
    completed_at = datetime('now')
WHERE id = ?
`

type CompleteTaskParams struct {
	ExitCode     sql.NullInt64  `json:"exit_code"`
	StdoutLog    sql.NullString `json:"stdout_log"`
	StderrLog    sql.NullString `json:"stderr_log"`
	FilesChanged sql.NullString `json:"files_changed"`
	ID           string         `json:"id"`
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, completeTask,
		arg.ExitCode,
		arg.StdoutLog,
		arg.StderrLog,
		arg.FilesChanged,
		arg.ID,
	)
	return err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (workflow_id, task_id, event_type, event_data)
VALUES (?, ?, ?, ?)
`

type CreateEventParams struct {
	WorkflowID sql.NullString `json:"workflow_id"`
	TaskID     sql.NullString `json:"task_id"`
	EventType  string         `json:"event_type"`
	EventData  sql.NullString `json:"event_data"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.WorkflowID,
		arg.TaskID,
		arg.EventType,
		arg.EventData,
	)
	return err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (
    id, workflow_id, sequence_num, task_type, agent_type, target_repo,
    input_artifact, state, max_attempts
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ID            string `json:"id"`
	WorkflowID    string `json:"workflow_id"`
	SequenceNum   int64  `json:"sequence_num"`
	TaskType      string `json:"task_type"`
	AgentType     string `json:"agent_type"`
	TargetRepo    string `json:"target_repo"`
	InputArtifact string `json:"input_artifact"`
	State         string `json:"state"`
	MaxAttempts   int64  `json:"max_attempts"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.WorkflowID,
		arg.SequenceNum,
		arg.TaskType,
		arg.AgentType,
		arg.TargetRepo,
		arg.InputArtifact,
		arg.State,
		arg.MaxAttempts,
	)
	return err
}

const createWorkflow = `-- name: CreateWorkflow :exec
INSERT INTO workflows (
    id, original_intent, original_file, current_state, target_repo, git_branch,
    max_depth, max_files_changed, max_duration_mins
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkflowParams struct {
	ID              string `json:"id"`
	OriginalIntent  string `json:"original_intent"`
	OriginalFile    string `json:"original_file"`
	CurrentState    string `json:"current_state"`
	TargetRepo      string `json:"target_repo"`
	GitBranch       string `json:"git_branch"`
	MaxDepth        int64  `json:"max_depth"`
	MaxFilesChanged int64  `json:"max_files_changed"`
	MaxDurationMins int64  `json:"max_duration_mins"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, createWorkflow,
		arg.ID,
		arg.OriginalIntent,
		arg.OriginalFile,
		arg.CurrentState,
		arg.TargetRepo,
		arg.GitBranch,
		arg.MaxDepth,
		arg.MaxFilesChanged,
		arg.MaxDurationMins,
	)
	return err
}

const failTask = `-- name: FailTask :exec
UPDATE tasks
SET state = 'failed',
    error_message = ?,
    completed_at = datetime('now')
WHERE id = ?
`

type FailTaskParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) error {
	_, err := q.db.ExecContext(ctx, failTask, arg.ErrorMessage, arg.ID)
	return err
}

const getPendingTask = `-- name: GetPendingTask :one
SELECT id FROM tasks
WHERE state = 'pending'
ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) GetPendingTask(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getPendingTask)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getTask = `-- name: GetTask :one
SELECT id, workflow_id, sequence_num, task_type, agent_type, target_repo, input_artifact, output_artifact, state, claimed_by, claimed_at, attempts, max_attempts, exit_code, stdout_log, stderr_log, files_changed, created_at, started_at, completed_at, error_message FROM tasks WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.SequenceNum,
		&i.TaskType,
		&i.AgentType,
		&i.TargetRepo,
		&i.InputArtifact,
		&i.OutputArtifact,
		&i.State,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExitCode,
		&i.StdoutLog,
		&i.StderrLog,
		&i.FilesChanged,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, original_intent, original_file, current_state, target_repo, git_branch, max_depth, max_files_changed, max_duration_mins, current_depth, files_changed, started_at, created_at, updated_at, completed_at, error_message FROM workflows WHERE id = ? LIMIT 1
`

func (q *Queries) GetWorkflow(ctx context.Context, id string) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OriginalIntent,
		&i.OriginalFile,
		&i.CurrentState,
		&i.TargetRepo,
		&i.GitBranch,
		&i.MaxDepth,
		&i.MaxFilesChanged,
		&i.MaxDurationMins,
		&i.CurrentDepth,
		&i.FilesChanged,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, workflow_id, task_id, event_type, event_data, created_at FROM events
WHERE workflow_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListEvents(ctx context.Context, workflowID sql.NullString) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.TaskID,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTask = `-- name: ReleaseTask :exec
UPDATE tasks
SET state = 'pending', claimed_by = NULL, claimed_at = NULL
WHERE id = ?
`

func (q *Queries) ReleaseTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, releaseTask, id)
	return err
}

const retryTask = `-- name: RetryTask :exec
UPDATE tasks
SET state = 'pending',
    claimed_by = NULL,
    claimed_at = NULL,
    attempts = attempts + 1
WHERE id = ?
`

func (q *Queries) RetryTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, retryTask, id)
	return err
}

const updateWorkflowBudget = `-- name: UpdateWorkflowBudget :exec
UPDATE workflows
SET current_depth = ?, files_changed = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateWorkflowBudgetParams struct {
	CurrentDepth int64  `json:"current_depth"`
	FilesChanged int64  `json:"files_changed"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateWorkflowBudget(ctx context.Context, arg UpdateWorkflowBudgetParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowBudget, arg.CurrentDepth, arg.FilesChanged, arg.ID)
	return err
}

const updateWorkflowState = `-- name: UpdateWorkflowState :exec
UPDATE workflows
SET current_state = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateWorkflowStateParams struct {
	CurrentState string `json:"current_state"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateWorkflowState(ctx context.Context, arg UpdateWorkflowStateParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowState, arg.CurrentState, arg.ID)
	return err
}
