// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"database/sql"
)

type Artifact struct {
	ID           string         `json:"id"`
	SessionID    sql.NullString `json:"session_id"`
	WorkflowID   sql.NullString `json:"workflow_id"`
	TaskID       sql.NullString `json:"task_id"`
	ArtifactType string         `json:"artifact_type"`
	Path         string         `json:"path"`
	SizeBytes    sql.NullInt64  `json:"size_bytes"`
	MetadataJson sql.NullString `json:"metadata_json"`
	CreatedAt    string         `json:"created_at"`
}

type Event struct {
	ID         int64          `json:"id"`
	WorkflowID sql.NullString `json:"workflow_id"`
	TaskID     sql.NullString `json:"task_id"`
	EventType  string         `json:"event_type"`
	EventData  sql.NullString `json:"event_data"`
	CreatedAt  string         `json:"created_at"`
}

type PipelineRun struct {
	ID                       string          `json:"id"`
	SessionID                sql.NullString  `json:"session_id"`
	WorkflowID               string          `json:"workflow_id"`
	Project                  string          `json:"project"`
	WorkOrderType            sql.NullString  `json:"work_order_type"`
	ScopeStartedAt           sql.NullString  `json:"scope_started_at"`
	ScopeCompletedAt         sql.NullString  `json:"scope_completed_at"`
	BuildStartedAt           sql.NullString  `json:"build_started_at"`
	BuildCompletedAt         sql.NullString  `json:"build_completed_at"`
	VerifyStartedAt          sql.NullString  `json:"verify_started_at"`
	VerifyCompletedAt        sql.NullString  `json:"verify_completed_at"`
	ScopeModel               sql.NullString  `json:"scope_model"`
	BuildModel               sql.NullString  `json:"build_model"`
	VerifyModel              sql.NullString  `json:"verify_model"`
	ScopeFilesSuggested      sql.NullInt64   `json:"scope_files_suggested"`
	BuildFilesChanged        sql.NullInt64   `json:"build_files_changed"`
	BuildScopeDrift          int64           `json:"build_scope_drift"`
	ScopeEstimatedComplexity sql.NullString  `json:"scope_estimated_complexity"`
	ScopeRagDirect           sql.NullInt64   `json:"scope_rag_direct"`
	ScopeRagHops             sql.NullInt64   `json:"scope_rag_hops"`
	ScopePathsStripped       sql.NullInt64   `json:"scope_paths_stripped"`
	ScopePathsReclassified   sql.NullInt64   `json:"scope_paths_reclassified"`
	VerifyResult             sql.NullString  `json:"verify_result"`
	HumanResult              sql.NullString  `json:"human_result"`
	WorkOrderContent         sql.NullString  `json:"work_order_content"`
	ScopeTokensIn            sql.NullInt64   `json:"scope_tokens_in"`
	ScopeTokensOut           sql.NullInt64   `json:"scope_tokens_out"`
	BuildTokensIn            sql.NullInt64   `json:"build_tokens_in"`
	BuildTokensOut           sql.NullInt64   `json:"build_tokens_out"`
	VerifyTokensIn           sql.NullInt64   `json:"verify_tokens_in"`
	VerifyTokensOut          sql.NullInt64   `json:"verify_tokens_out"`
	BuildCostUsd             sql.NullFloat64 `json:"build_cost_usd"`
	BuildSessionID           sql.NullString  `json:"build_session_id"`
	BuildToolCalls           sql.NullString  `json:"build_tool_calls"`
	BuildClaudeMdContent     sql.NullString  `json:"build_claude_md_content"`
	CreatedAt                string          `json:"created_at"`
	UpdatedAt                string          `json:"updated_at"`
}

type PlanRun struct {
	ID                       string          `json:"id"`
	SessionID                sql.NullString  `json:"session_id"`
	SpecFile                 string          `json:"spec_file"`
	Project                  sql.NullString  `json:"project"`
	SpecFingerprint          sql.NullString  `json:"spec_fingerprint"`
	GenerationModel          sql.NullString  `json:"generation_model"`
	AuditModel               sql.NullString  `json:"audit_model"`
	GenerationSessionID      sql.NullString  `json:"generation_session_id"`
	AuditSessionID           sql.NullString  `json:"audit_session_id"`
	WorkOrdersGenerated      sql.NullInt64   `json:"work_orders_generated"`
	PreAuditWorkOrderCount   sql.NullInt64   `json:"pre_audit_work_order_count"`
	PostAuditWorkOrderCount  sql.NullInt64   `json:"post_audit_work_order_count"`
	AuditChangeText          sql.NullString  `json:"audit_change_text"`
	AuditWorkOrdersAdded     sql.NullInt64   `json:"audit_work_orders_added"`
	AuditWorkOrdersModified  sql.NullInt64   `json:"audit_work_orders_modified"`
	AuditWorkOrdersUnchanged sql.NullInt64   `json:"audit_work_orders_unchanged"`
	GenerationCostUsd        sql.NullFloat64 `json:"generation_cost_usd"`
	AuditCostUsd             sql.NullFloat64 `json:"audit_cost_usd"`
	GenerationDurationMs     sql.NullInt64   `json:"generation_duration_ms"`
	AuditDurationMs          sql.NullInt64   `json:"audit_duration_ms"`
	GenerationRetryCount     int64           `json:"generation_retry_count"`
	AuditTokensIn            sql.NullInt64   `json:"audit_tokens_in"`
	AuditTokensOut           sql.NullInt64   `json:"audit_tokens_out"`
	GenerationTokensIn       sql.NullInt64   `json:"generation_tokens_in"`
	GenerationTokensOut      sql.NullInt64   `json:"generation_tokens_out"`
	CreatedAt                string          `json:"created_at"`
}

type Session struct {
	ID             string         `json:"id"`
	Kind           string         `json:"kind"`
	Project        string         `json:"project"`
	SourceSpecPath sql.NullString `json:"source_spec_path"`
	State          string         `json:"state"`
	ErrorMessage   sql.NullString `json:"error_message"`
	StartedAt      sql.NullString `json:"started_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type SubCall struct {
	ID               int64          `json:"id"`
	PipelineRunID    string         `json:"pipeline_run_id"`
	Phase            string         `json:"phase"`
	Step             string         `json:"step"`
	TargetPath       sql.NullString `json:"target_path"`
	Provider         string         `json:"provider"`
	Model            string         `json:"model"`
	TokensIn         int64          `json:"tokens_in"`
	TokensOut        int64          `json:"tokens_out"`
	LatencyMs        int64          `json:"latency_ms"`
	EstimatedCostUsd float64        `json:"estimated_cost_usd"`
	Success          int64          `json:"success"`
	ErrorMessage     sql.NullString `json:"error_message"`
	CreatedAt        string         `json:"created_at"`
}

type Task struct {
	ID             string         `json:"id"`
	WorkflowID     string         `json:"workflow_id"`
	SequenceNum    int64          `json:"sequence_num"`
	TaskType       string         `json:"task_type"`
	AgentType      string         `json:"agent_type"`
	TargetRepo     string         `json:"target_repo"`
	Phase          string         `json:"phase"`
	InputArtifact  string         `json:"input_artifact"`
	OutputArtifact sql.NullString `json:"output_artifact"`
	State          string         `json:"state"`
	ClaimedBy      sql.NullString `json:"claimed_by"`
	ClaimedAt      sql.NullString `json:"claimed_at"`
	Attempts       int64          `json:"attempts"`
	MaxAttempts    int64          `json:"max_attempts"`
	ExitCode       sql.NullInt64  `json:"exit_code"`
	StdoutLog      sql.NullString `json:"stdout_log"`
	StderrLog      sql.NullString `json:"stderr_log"`
	FilesChanged   sql.NullString `json:"files_changed"`
	CreatedAt      string         `json:"created_at"`
	StartedAt      sql.NullString `json:"started_at"`
	CompletedAt    sql.NullString `json:"completed_at"`
	ErrorMessage   sql.NullString `json:"error_message"`
}

type Workflow struct {
	ID                     string         `json:"id"`
	OriginalIntent         string         `json:"original_intent"`
	OriginalFile           string         `json:"original_file"`
	CurrentState           string         `json:"current_state"`
	TargetRepo             string         `json:"target_repo"`
	GitBranch              string         `json:"git_branch"`
	ContextPackagePath     sql.NullString `json:"context_package_path"`
	VerificationReportPath sql.NullString `json:"verification_report_path"`
	MaxDepth               int64          `json:"max_depth"`
	MaxFilesChanged        int64          `json:"max_files_changed"`
	MaxDurationMins        int64          `json:"max_duration_mins"`
	CurrentDepth           int64          `json:"current_depth"`
	FilesChanged           int64          `json:"files_changed"`
	StartedAt              sql.NullString `json:"started_at"`
	CreatedAt              string         `json:"created_at"`
	UpdatedAt              string         `json:"updated_at"`
	CompletedAt            sql.NullString `json:"completed_at"`
	ErrorMessage           sql.NullString `json:"error_message"`
}
