// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const claimTask = `-- name: ClaimTask :execrows
UPDATE tasks
SET state = 'claimed', claimed_by = ?, claimed_at = datetime('now')
WHERE id = ? AND state = 'pending'
`

type ClaimTaskParams struct {
	ClaimedBy sql.NullString `json:"claimed_by"`
	ID        string         `json:"id"`
}

func (q *Queries) ClaimTask(ctx context.Context, arg ClaimTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimTask, arg.ClaimedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeTask = `-- name: CompleteTask :exec
UPDATE tasks
SET state = 'completed',
    exit_code = ?,
    stdout_log = ?,
    stderr_log = ?,
    files_changed = ?,
    completed_at = datetime('now')
WHERE id = ?
`

type CompleteTaskParams struct {
	ExitCode     sql.NullInt64  `json:"exit_code"`
	StdoutLog    sql.NullString `json:"stdout_log"`
	StderrLog    sql.NullString `json:"stderr_log"`
	FilesChanged sql.NullString `json:"files_changed"`
	ID           string         `json:"id"`
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) error {
	_, err := q.db.ExecContext(ctx, completeTask,
		arg.ExitCode,
		arg.StdoutLog,
		arg.StderrLog,
		arg.FilesChanged,
		arg.ID,
	)
	return err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (workflow_id, task_id, event_type, event_data)
VALUES (?, ?, ?, ?)
`

type CreateEventParams struct {
	WorkflowID sql.NullString `json:"workflow_id"`
	TaskID     sql.NullString `json:"task_id"`
	EventType  string         `json:"event_type"`
	EventData  sql.NullString `json:"event_data"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.WorkflowID,
		arg.TaskID,
		arg.EventType,
		arg.EventData,
	)
	return err
}

const createPipelineRun = `-- name: CreatePipelineRun :exec
INSERT INTO pipeline_runs (id, workflow_id, project, work_order_type)
VALUES (?, ?, ?, ?)
`

type CreatePipelineRunParams struct {
	ID            string         `json:"id"`
	WorkflowID    string         `json:"workflow_id"`
	Project       string         `json:"project"`
	WorkOrderType sql.NullString `json:"work_order_type"`
}

func (q *Queries) CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) error {
	_, err := q.db.ExecContext(ctx, createPipelineRun,
		arg.ID,
		arg.WorkflowID,
		arg.Project,
		arg.WorkOrderType,
	)
	return err
}

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (
    id, workflow_id, sequence_num, task_type, agent_type, target_repo,
    phase, input_artifact, state, max_attempts
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ID            string `json:"id"`
	WorkflowID    string `json:"workflow_id"`
	SequenceNum   int64  `json:"sequence_num"`
	TaskType      string `json:"task_type"`
	AgentType     string `json:"agent_type"`
	TargetRepo    string `json:"target_repo"`
	Phase         string `json:"phase"`
	InputArtifact string `json:"input_artifact"`
	State         string `json:"state"`
	MaxAttempts   int64  `json:"max_attempts"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.WorkflowID,
		arg.SequenceNum,
		arg.TaskType,
		arg.AgentType,
		arg.TargetRepo,
		arg.Phase,
		arg.InputArtifact,
		arg.State,
		arg.MaxAttempts,
	)
	return err
}

const createWorkflow = `-- name: CreateWorkflow :exec
INSERT INTO workflows (
    id, original_intent, original_file, current_state, target_repo, git_branch,
    context_package_path, verification_report_path,
    max_depth, max_files_changed, max_duration_mins
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateWorkflowParams struct {
	ID                     string         `json:"id"`
	OriginalIntent         string         `json:"original_intent"`
	OriginalFile           string         `json:"original_file"`
	CurrentState           string         `json:"current_state"`
	TargetRepo             string         `json:"target_repo"`
	GitBranch              string         `json:"git_branch"`
	ContextPackagePath     sql.NullString `json:"context_package_path"`
	VerificationReportPath sql.NullString `json:"verification_report_path"`
	MaxDepth               int64          `json:"max_depth"`
	MaxFilesChanged        int64          `json:"max_files_changed"`
	MaxDurationMins        int64          `json:"max_duration_mins"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) error {
	_, err := q.db.ExecContext(ctx, createWorkflow,
		arg.ID,
		arg.OriginalIntent,
		arg.OriginalFile,
		arg.CurrentState,
		arg.TargetRepo,
		arg.GitBranch,
		arg.ContextPackagePath,
		arg.VerificationReportPath,
		arg.MaxDepth,
		arg.MaxFilesChanged,
		arg.MaxDurationMins,
	)
	return err
}

const failTask = `-- name: FailTask :exec
UPDATE tasks
SET state = 'failed',
    error_message = ?,
    completed_at = datetime('now')
WHERE id = ?
`

type FailTaskParams struct {
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) error {
	_, err := q.db.ExecContext(ctx, failTask, arg.ErrorMessage, arg.ID)
	return err
}

const getPendingTask = `-- name: GetPendingTask :one
SELECT id FROM tasks
WHERE state = 'pending'
ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) GetPendingTask(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getPendingTask)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getPipelineRunIDByWorkflowID = `-- name: GetPipelineRunIDByWorkflowID :one
SELECT id FROM pipeline_runs WHERE workflow_id = ? LIMIT 1
`

func (q *Queries) GetPipelineRunIDByWorkflowID(ctx context.Context, workflowID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPipelineRunIDByWorkflowID, workflowID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getPipelineStats = `-- name: GetPipelineStats :one
SELECT
    COUNT(*)                                                                AS total_runs,
    SUM(CASE WHEN verify_result = 'PASS' THEN 1 ELSE 0 END)               AS verify_pass,
    SUM(CASE WHEN verify_result = 'WARN' THEN 1 ELSE 0 END)               AS verify_warn,
    SUM(CASE WHEN verify_result = 'FAIL' THEN 1 ELSE 0 END)               AS verify_fail,
    SUM(CASE WHEN human_result = 'approved' THEN 1 ELSE 0 END)            AS human_approved,
    SUM(CASE WHEN human_result = 'rejected' THEN 1 ELSE 0 END)            AS human_rejected,
    SUM(CASE WHEN human_result IS NULL THEN 1 ELSE 0 END)                 AS human_pending,
    AVG(CASE
        WHEN scope_started_at IS NOT NULL AND scope_completed_at IS NOT NULL
        THEN CAST(strftime('%s', scope_completed_at) AS INTEGER) - CAST(strftime('%s', scope_started_at) AS INTEGER)
    END)                                                                    AS avg_scope_secs,
    AVG(CASE
        WHEN build_started_at IS NOT NULL AND build_completed_at IS NOT NULL
        THEN CAST(strftime('%s', build_completed_at) AS INTEGER) - CAST(strftime('%s', build_started_at) AS INTEGER)
    END)                                                                    AS avg_build_secs,
    AVG(CASE
        WHEN verify_started_at IS NOT NULL AND verify_completed_at IS NOT NULL
        THEN CAST(strftime('%s', verify_completed_at) AS INTEGER) - CAST(strftime('%s', verify_started_at) AS INTEGER)
    END)                                                                    AS avg_verify_secs,
    SUM(COALESCE(scope_tokens_in, 0))                                      AS total_scope_tokens_in,
    SUM(COALESCE(scope_tokens_out, 0))                                     AS total_scope_tokens_out,
    SUM(COALESCE(build_tokens_in, 0))                                      AS total_build_tokens_in,
    SUM(COALESCE(build_tokens_out, 0))                                     AS total_build_tokens_out,
    SUM(COALESCE(verify_tokens_in, 0))                                     AS total_verify_tokens_in,
    SUM(COALESCE(verify_tokens_out, 0))                                    AS total_verify_tokens_out,
    SUM(COALESCE(build_cost_usd, 0))                                       AS total_build_cost_usd
FROM pipeline_runs
`

type GetPipelineStatsRow struct {
	TotalRuns            int64           `json:"total_runs"`
	VerifyPass           sql.NullFloat64 `json:"verify_pass"`
	VerifyWarn           sql.NullFloat64 `json:"verify_warn"`
	VerifyFail           sql.NullFloat64 `json:"verify_fail"`
	HumanApproved        sql.NullFloat64 `json:"human_approved"`
	HumanRejected        sql.NullFloat64 `json:"human_rejected"`
	HumanPending         sql.NullFloat64 `json:"human_pending"`
	AvgScopeSecs         sql.NullFloat64 `json:"avg_scope_secs"`
	AvgBuildSecs         sql.NullFloat64 `json:"avg_build_secs"`
	AvgVerifySecs        sql.NullFloat64 `json:"avg_verify_secs"`
	TotalScopeTokensIn   sql.NullFloat64 `json:"total_scope_tokens_in"`
	TotalScopeTokensOut  sql.NullFloat64 `json:"total_scope_tokens_out"`
	TotalBuildTokensIn   sql.NullFloat64 `json:"total_build_tokens_in"`
	TotalBuildTokensOut  sql.NullFloat64 `json:"total_build_tokens_out"`
	TotalVerifyTokensIn  sql.NullFloat64 `json:"total_verify_tokens_in"`
	TotalVerifyTokensOut sql.NullFloat64 `json:"total_verify_tokens_out"`
	TotalBuildCostUsd    sql.NullFloat64 `json:"total_build_cost_usd"`
}

func (q *Queries) GetPipelineStats(ctx context.Context) (GetPipelineStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getPipelineStats)
	var i GetPipelineStatsRow
	err := row.Scan(
		&i.TotalRuns,
		&i.VerifyPass,
		&i.VerifyWarn,
		&i.VerifyFail,
		&i.HumanApproved,
		&i.HumanRejected,
		&i.HumanPending,
		&i.AvgScopeSecs,
		&i.AvgBuildSecs,
		&i.AvgVerifySecs,
		&i.TotalScopeTokensIn,
		&i.TotalScopeTokensOut,
		&i.TotalBuildTokensIn,
		&i.TotalBuildTokensOut,
		&i.TotalVerifyTokensIn,
		&i.TotalVerifyTokensOut,
		&i.TotalBuildCostUsd,
	)
	return i, err
}

const getRecentPipelineRuns = `-- name: GetRecentPipelineRuns :many
SELECT
    workflow_id,
    work_order_type,
    verify_result,
    human_result,
    scope_estimated_complexity,
    CASE
        WHEN verify_result IS NULL OR human_result IS NULL THEN ''
        WHEN verify_result = 'PASS' AND human_result = 'approved' THEN 'match'
        WHEN verify_result = 'WARN' THEN 'match'
        WHEN verify_result = 'FAIL' AND human_result = 'rejected' THEN 'match'
        ELSE 'mismatch'
    END AS agreement,
    COALESCE(scope_tokens_in, 0) + COALESCE(scope_tokens_out, 0) +
    COALESCE(build_tokens_in, 0) + COALESCE(build_tokens_out, 0) +
    COALESCE(verify_tokens_in, 0) + COALESCE(verify_tokens_out, 0) AS total_tokens
FROM pipeline_runs
ORDER BY created_at DESC
LIMIT 5
`

type GetRecentPipelineRunsRow struct {
	WorkflowID               string         `json:"workflow_id"`
	WorkOrderType            sql.NullString `json:"work_order_type"`
	VerifyResult             sql.NullString `json:"verify_result"`
	HumanResult              sql.NullString `json:"human_result"`
	ScopeEstimatedComplexity sql.NullString `json:"scope_estimated_complexity"`
	Agreement                string         `json:"agreement"`
	TotalTokens              int64          `json:"total_tokens"`
}

func (q *Queries) GetRecentPipelineRuns(ctx context.Context) ([]GetRecentPipelineRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentPipelineRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentPipelineRunsRow
	for rows.Next() {
		var i GetRecentPipelineRunsRow
		if err := rows.Scan(
			&i.WorkflowID,
			&i.WorkOrderType,
			&i.VerifyResult,
			&i.HumanResult,
			&i.ScopeEstimatedComplexity,
			&i.Agreement,
			&i.TotalTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScopeQualityStats = `-- name: GetScopeQualityStats :one
SELECT
    AVG(scope_paths_stripped) AS avg_paths_stripped,
    AVG(scope_paths_reclassified) AS avg_paths_reclassified,
    SUM(CASE WHEN scope_estimated_complexity = 'low' THEN 1 ELSE 0 END) AS complexity_low,
    SUM(CASE WHEN scope_estimated_complexity = 'medium' THEN 1 ELSE 0 END) AS complexity_medium,
    SUM(CASE WHEN scope_estimated_complexity = 'high' THEN 1 ELSE 0 END) AS complexity_high
FROM pipeline_runs
`

type GetScopeQualityStatsRow struct {
	AvgPathsStripped     sql.NullFloat64 `json:"avg_paths_stripped"`
	AvgPathsReclassified sql.NullFloat64 `json:"avg_paths_reclassified"`
	ComplexityLow        sql.NullFloat64 `json:"complexity_low"`
	ComplexityMedium     sql.NullFloat64 `json:"complexity_medium"`
	ComplexityHigh       sql.NullFloat64 `json:"complexity_high"`
}

func (q *Queries) GetScopeQualityStats(ctx context.Context) (GetScopeQualityStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getScopeQualityStats)
	var i GetScopeQualityStatsRow
	err := row.Scan(
		&i.AvgPathsStripped,
		&i.AvgPathsReclassified,
		&i.ComplexityLow,
		&i.ComplexityMedium,
		&i.ComplexityHigh,
	)
	return i, err
}

const getStatsByWorkOrderType = `-- name: GetStatsByWorkOrderType :many
SELECT
    work_order_type,
    COUNT(*) AS total,
    SUM(CASE WHEN verify_result = 'PASS' THEN 1 ELSE 0 END) AS verify_pass,
    SUM(CASE WHEN verify_result = 'WARN' THEN 1 ELSE 0 END) AS verify_warn,
    SUM(CASE WHEN verify_result = 'FAIL' THEN 1 ELSE 0 END) AS verify_fail,
    SUM(CASE WHEN human_result = 'approved' THEN 1 ELSE 0 END) AS human_approved,
    SUM(CASE WHEN human_result = 'rejected' THEN 1 ELSE 0 END) AS human_rejected,
    AVG(CASE
        WHEN scope_started_at IS NOT NULL AND scope_completed_at IS NOT NULL
        THEN CAST(strftime('%s', scope_completed_at) AS INTEGER) - CAST(strftime('%s', scope_started_at) AS INTEGER)
    END) AS avg_scope_secs
FROM pipeline_runs
WHERE work_order_type IS NOT NULL
GROUP BY work_order_type
`

type GetStatsByWorkOrderTypeRow struct {
	WorkOrderType sql.NullString  `json:"work_order_type"`
	Total         int64           `json:"total"`
	VerifyPass    sql.NullFloat64 `json:"verify_pass"`
	VerifyWarn    sql.NullFloat64 `json:"verify_warn"`
	VerifyFail    sql.NullFloat64 `json:"verify_fail"`
	HumanApproved sql.NullFloat64 `json:"human_approved"`
	HumanRejected sql.NullFloat64 `json:"human_rejected"`
	AvgScopeSecs  sql.NullFloat64 `json:"avg_scope_secs"`
}

func (q *Queries) GetStatsByWorkOrderType(ctx context.Context) ([]GetStatsByWorkOrderTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getStatsByWorkOrderType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStatsByWorkOrderTypeRow
	for rows.Next() {
		var i GetStatsByWorkOrderTypeRow
		if err := rows.Scan(
			&i.WorkOrderType,
			&i.Total,
			&i.VerifyPass,
			&i.VerifyWarn,
			&i.VerifyFail,
			&i.HumanApproved,
			&i.HumanRejected,
			&i.AvgScopeSecs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubCallAggregatesByProvider = `-- name: GetSubCallAggregatesByProvider :many
SELECT
    provider,
    SUM(tokens_in) AS total_tokens_in,
    SUM(tokens_out) AS total_tokens_out,
    SUM(estimated_cost_usd) AS total_estimated_cost_usd,
    COUNT(*) AS call_count
FROM sub_calls
WHERE pipeline_run_id = ?
GROUP BY provider
`

type GetSubCallAggregatesByProviderRow struct {
	Provider              string          `json:"provider"`
	TotalTokensIn         sql.NullFloat64 `json:"total_tokens_in"`
	TotalTokensOut        sql.NullFloat64 `json:"total_tokens_out"`
	TotalEstimatedCostUsd sql.NullFloat64 `json:"total_estimated_cost_usd"`
	CallCount             int64           `json:"call_count"`
}

func (q *Queries) GetSubCallAggregatesByProvider(ctx context.Context, pipelineRunID string) ([]GetSubCallAggregatesByProviderRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubCallAggregatesByProvider, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubCallAggregatesByProviderRow
	for rows.Next() {
		var i GetSubCallAggregatesByProviderRow
		if err := rows.Scan(
			&i.Provider,
			&i.TotalTokensIn,
			&i.TotalTokensOut,
			&i.TotalEstimatedCostUsd,
			&i.CallCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubCallGlobalStatsByProvider = `-- name: GetSubCallGlobalStatsByProvider :many
SELECT
    provider,
    SUM(tokens_in) AS total_tokens_in,
    SUM(tokens_out) AS total_tokens_out,
    SUM(estimated_cost_usd) AS total_estimated_cost_usd,
    COUNT(*) AS call_count
FROM sub_calls
GROUP BY provider
`

type GetSubCallGlobalStatsByProviderRow struct {
	Provider              string          `json:"provider"`
	TotalTokensIn         sql.NullFloat64 `json:"total_tokens_in"`
	TotalTokensOut        sql.NullFloat64 `json:"total_tokens_out"`
	TotalEstimatedCostUsd sql.NullFloat64 `json:"total_estimated_cost_usd"`
	CallCount             int64           `json:"call_count"`
}

func (q *Queries) GetSubCallGlobalStatsByProvider(ctx context.Context) ([]GetSubCallGlobalStatsByProviderRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubCallGlobalStatsByProvider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubCallGlobalStatsByProviderRow
	for rows.Next() {
		var i GetSubCallGlobalStatsByProviderRow
		if err := rows.Scan(
			&i.Provider,
			&i.TotalTokensIn,
			&i.TotalTokensOut,
			&i.TotalEstimatedCostUsd,
			&i.CallCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubCallPhaseAverages = `-- name: GetSubCallPhaseAverages :many
SELECT
    phase,
    COUNT(*) AS total_calls,
    COUNT(DISTINCT pipeline_run_id) AS run_count
FROM sub_calls
GROUP BY phase
`

type GetSubCallPhaseAveragesRow struct {
	Phase      string `json:"phase"`
	TotalCalls int64  `json:"total_calls"`
	RunCount   int64  `json:"run_count"`
}

func (q *Queries) GetSubCallPhaseAverages(ctx context.Context) ([]GetSubCallPhaseAveragesRow, error) {
	rows, err := q.db.QueryContext(ctx, getSubCallPhaseAverages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubCallPhaseAveragesRow
	for rows.Next() {
		var i GetSubCallPhaseAveragesRow
		if err := rows.Scan(&i.Phase, &i.TotalCalls, &i.RunCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubCallsByPipelineRun = `-- name: GetSubCallsByPipelineRun :many
SELECT id, pipeline_run_id, phase, step, target_path,
       provider, model, tokens_in, tokens_out,
       latency_ms, estimated_cost_usd, success, error_message, created_at
FROM sub_calls
WHERE pipeline_run_id = ?
ORDER BY created_at
`

func (q *Queries) GetSubCallsByPipelineRun(ctx context.Context, pipelineRunID string) ([]SubCall, error) {
	rows, err := q.db.QueryContext(ctx, getSubCallsByPipelineRun, pipelineRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubCall
	for rows.Next() {
		var i SubCall
		if err := rows.Scan(
			&i.ID,
			&i.PipelineRunID,
			&i.Phase,
			&i.Step,
			&i.TargetPath,
			&i.Provider,
			&i.Model,
			&i.TokensIn,
			&i.TokensOut,
			&i.LatencyMs,
			&i.EstimatedCostUsd,
			&i.Success,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, workflow_id, sequence_num, task_type, agent_type, target_repo, phase, input_artifact, output_artifact, state, claimed_by, claimed_at, attempts, max_attempts, exit_code, stdout_log, stderr_log, files_changed, created_at, started_at, completed_at, error_message FROM tasks WHERE id = ? LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.SequenceNum,
		&i.TaskType,
		&i.AgentType,
		&i.TargetRepo,
		&i.Phase,
		&i.InputArtifact,
		&i.OutputArtifact,
		&i.State,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExitCode,
		&i.StdoutLog,
		&i.StderrLog,
		&i.FilesChanged,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getVerifyHumanAgreement = `-- name: GetVerifyHumanAgreement :many
SELECT
    verify_result,
    human_result,
    COUNT(*) AS count
FROM pipeline_runs
WHERE verify_result IS NOT NULL AND human_result IS NOT NULL
GROUP BY verify_result, human_result
`

type GetVerifyHumanAgreementRow struct {
	VerifyResult sql.NullString `json:"verify_result"`
	HumanResult  sql.NullString `json:"human_result"`
	Count        int64          `json:"count"`
}

func (q *Queries) GetVerifyHumanAgreement(ctx context.Context) ([]GetVerifyHumanAgreementRow, error) {
	rows, err := q.db.QueryContext(ctx, getVerifyHumanAgreement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVerifyHumanAgreementRow
	for rows.Next() {
		var i GetVerifyHumanAgreementRow
		if err := rows.Scan(&i.VerifyResult, &i.HumanResult, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, original_intent, original_file, current_state, target_repo, git_branch, context_package_path, verification_report_path, max_depth, max_files_changed, max_duration_mins, current_depth, files_changed, started_at, created_at, updated_at, completed_at, error_message FROM workflows WHERE id = ? LIMIT 1
`

func (q *Queries) GetWorkflow(ctx context.Context, id string) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflow, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.OriginalIntent,
		&i.OriginalFile,
		&i.CurrentState,
		&i.TargetRepo,
		&i.GitBranch,
		&i.ContextPackagePath,
		&i.VerificationReportPath,
		&i.MaxDepth,
		&i.MaxFilesChanged,
		&i.MaxDurationMins,
		&i.CurrentDepth,
		&i.FilesChanged,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const insertPlanRun = `-- name: InsertPlanRun :exec
INSERT INTO plan_runs (
    id, spec_file, project, spec_fingerprint,
    generation_model, audit_model,
    generation_session_id, audit_session_id,
    work_orders_generated,
    pre_audit_work_order_count, post_audit_work_order_count, audit_change_text,
    audit_work_orders_added, audit_work_orders_modified, audit_work_orders_unchanged,
    generation_cost_usd, audit_cost_usd,
    generation_duration_ms, audit_duration_ms,
    generation_retry_count,
    generation_tokens_in, generation_tokens_out,
    audit_tokens_in, audit_tokens_out
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertPlanRunParams struct {
	ID                       string          `json:"id"`
	SpecFile                 string          `json:"spec_file"`
	Project                  sql.NullString  `json:"project"`
	SpecFingerprint          sql.NullString  `json:"spec_fingerprint"`
	GenerationModel          sql.NullString  `json:"generation_model"`
	AuditModel               sql.NullString  `json:"audit_model"`
	GenerationSessionID      sql.NullString  `json:"generation_session_id"`
	AuditSessionID           sql.NullString  `json:"audit_session_id"`
	WorkOrdersGenerated      sql.NullInt64   `json:"work_orders_generated"`
	PreAuditWorkOrderCount   sql.NullInt64   `json:"pre_audit_work_order_count"`
	PostAuditWorkOrderCount  sql.NullInt64   `json:"post_audit_work_order_count"`
	AuditChangeText          sql.NullString  `json:"audit_change_text"`
	AuditWorkOrdersAdded     sql.NullInt64   `json:"audit_work_orders_added"`
	AuditWorkOrdersModified  sql.NullInt64   `json:"audit_work_orders_modified"`
	AuditWorkOrdersUnchanged sql.NullInt64   `json:"audit_work_orders_unchanged"`
	GenerationCostUsd        sql.NullFloat64 `json:"generation_cost_usd"`
	AuditCostUsd             sql.NullFloat64 `json:"audit_cost_usd"`
	GenerationDurationMs     sql.NullInt64   `json:"generation_duration_ms"`
	AuditDurationMs          sql.NullInt64   `json:"audit_duration_ms"`
	GenerationRetryCount     int64           `json:"generation_retry_count"`
	GenerationTokensIn       sql.NullInt64   `json:"generation_tokens_in"`
	GenerationTokensOut      sql.NullInt64   `json:"generation_tokens_out"`
	AuditTokensIn            sql.NullInt64   `json:"audit_tokens_in"`
	AuditTokensOut           sql.NullInt64   `json:"audit_tokens_out"`
}

func (q *Queries) InsertPlanRun(ctx context.Context, arg InsertPlanRunParams) error {
	_, err := q.db.ExecContext(ctx, insertPlanRun,
		arg.ID,
		arg.SpecFile,
		arg.Project,
		arg.SpecFingerprint,
		arg.GenerationModel,
		arg.AuditModel,
		arg.GenerationSessionID,
		arg.AuditSessionID,
		arg.WorkOrdersGenerated,
		arg.PreAuditWorkOrderCount,
		arg.PostAuditWorkOrderCount,
		arg.AuditChangeText,
		arg.AuditWorkOrdersAdded,
		arg.AuditWorkOrdersModified,
		arg.AuditWorkOrdersUnchanged,
		arg.GenerationCostUsd,
		arg.AuditCostUsd,
		arg.GenerationDurationMs,
		arg.AuditDurationMs,
		arg.GenerationRetryCount,
		arg.GenerationTokensIn,
		arg.GenerationTokensOut,
		arg.AuditTokensIn,
		arg.AuditTokensOut,
	)
	return err
}

const insertSubCall = `-- name: InsertSubCall :exec
INSERT INTO sub_calls (
    pipeline_run_id, phase, step, target_path,
    provider, model, tokens_in, tokens_out,
    latency_ms, estimated_cost_usd, success, error_message
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSubCallParams struct {
	PipelineRunID    string         `json:"pipeline_run_id"`
	Phase            string         `json:"phase"`
	Step             string         `json:"step"`
	TargetPath       sql.NullString `json:"target_path"`
	Provider         string         `json:"provider"`
	Model            string         `json:"model"`
	TokensIn         int64          `json:"tokens_in"`
	TokensOut        int64          `json:"tokens_out"`
	LatencyMs        int64          `json:"latency_ms"`
	EstimatedCostUsd float64        `json:"estimated_cost_usd"`
	Success          int64          `json:"success"`
	ErrorMessage     sql.NullString `json:"error_message"`
}

func (q *Queries) InsertSubCall(ctx context.Context, arg InsertSubCallParams) error {
	_, err := q.db.ExecContext(ctx, insertSubCall,
		arg.PipelineRunID,
		arg.Phase,
		arg.Step,
		arg.TargetPath,
		arg.Provider,
		arg.Model,
		arg.TokensIn,
		arg.TokensOut,
		arg.LatencyMs,
		arg.EstimatedCostUsd,
		arg.Success,
		arg.ErrorMessage,
	)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT id, workflow_id, task_id, event_type, event_data, created_at FROM events
WHERE workflow_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListEvents(ctx context.Context, workflowID sql.NullString) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, workflowID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.TaskID,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTask = `-- name: ReleaseTask :exec
UPDATE tasks
SET state = 'pending', claimed_by = NULL, claimed_at = NULL
WHERE id = ?
`

func (q *Queries) ReleaseTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, releaseTask, id)
	return err
}

const retryTask = `-- name: RetryTask :exec
UPDATE tasks
SET state = 'pending',
    claimed_by = NULL,
    claimed_at = NULL,
    attempts = attempts + 1
WHERE id = ?
`

func (q *Queries) RetryTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, retryTask, id)
	return err
}

const updatePipelineRunBuild = `-- name: UpdatePipelineRunBuild :exec
UPDATE pipeline_runs
SET build_started_at = ?, build_completed_at = ?,
    build_files_changed = ?,
    build_tokens_in = ?, build_tokens_out = ?,
    build_model = ?,
    build_cost_usd = ?, build_session_id = ?,
    build_tool_calls = ?,
    updated_at = datetime('now')
WHERE workflow_id = ?
`

type UpdatePipelineRunBuildParams struct {
	BuildStartedAt    sql.NullString  `json:"build_started_at"`
	BuildCompletedAt  sql.NullString  `json:"build_completed_at"`
	BuildFilesChanged sql.NullInt64   `json:"build_files_changed"`
	BuildTokensIn     sql.NullInt64   `json:"build_tokens_in"`
	BuildTokensOut    sql.NullInt64   `json:"build_tokens_out"`
	BuildModel        sql.NullString  `json:"build_model"`
	BuildCostUsd      sql.NullFloat64 `json:"build_cost_usd"`
	BuildSessionID    sql.NullString  `json:"build_session_id"`
	BuildToolCalls    sql.NullString  `json:"build_tool_calls"`
	WorkflowID        string          `json:"workflow_id"`
}

func (q *Queries) UpdatePipelineRunBuild(ctx context.Context, arg UpdatePipelineRunBuildParams) error {
	_, err := q.db.ExecContext(ctx, updatePipelineRunBuild,
		arg.BuildStartedAt,
		arg.BuildCompletedAt,
		arg.BuildFilesChanged,
		arg.BuildTokensIn,
		arg.BuildTokensOut,
		arg.BuildModel,
		arg.BuildCostUsd,
		arg.BuildSessionID,
		arg.BuildToolCalls,
		arg.WorkflowID,
	)
	return err
}

const updatePipelineRunHumanResult = `-- name: UpdatePipelineRunHumanResult :exec
UPDATE pipeline_runs
SET human_result = ?, updated_at = datetime('now')
WHERE workflow_id = ?
`

type UpdatePipelineRunHumanResultParams struct {
	HumanResult sql.NullString `json:"human_result"`
	WorkflowID  string         `json:"workflow_id"`
}

func (q *Queries) UpdatePipelineRunHumanResult(ctx context.Context, arg UpdatePipelineRunHumanResultParams) error {
	_, err := q.db.ExecContext(ctx, updatePipelineRunHumanResult, arg.HumanResult, arg.WorkflowID)
	return err
}

const updatePipelineRunScope = `-- name: UpdatePipelineRunScope :exec
UPDATE pipeline_runs
SET scope_started_at = ?, scope_completed_at = ?,
    scope_tokens_in = ?, scope_tokens_out = ?,
    scope_model = ?,
    scope_files_suggested = ?,
    scope_estimated_complexity = ?,
    scope_rag_direct = ?, scope_rag_hops = ?,
    scope_paths_stripped = ?, scope_paths_reclassified = ?,
    updated_at = datetime('now')
WHERE workflow_id = ?
`

type UpdatePipelineRunScopeParams struct {
	ScopeStartedAt           sql.NullString `json:"scope_started_at"`
	ScopeCompletedAt         sql.NullString `json:"scope_completed_at"`
	ScopeTokensIn            sql.NullInt64  `json:"scope_tokens_in"`
	ScopeTokensOut           sql.NullInt64  `json:"scope_tokens_out"`
	ScopeModel               sql.NullString `json:"scope_model"`
	ScopeFilesSuggested      sql.NullInt64  `json:"scope_files_suggested"`
	ScopeEstimatedComplexity sql.NullString `json:"scope_estimated_complexity"`
	ScopeRagDirect           sql.NullInt64  `json:"scope_rag_direct"`
	ScopeRagHops             sql.NullInt64  `json:"scope_rag_hops"`
	ScopePathsStripped       sql.NullInt64  `json:"scope_paths_stripped"`
	ScopePathsReclassified   sql.NullInt64  `json:"scope_paths_reclassified"`
	WorkflowID               string         `json:"workflow_id"`
}

func (q *Queries) UpdatePipelineRunScope(ctx context.Context, arg UpdatePipelineRunScopeParams) error {
	_, err := q.db.ExecContext(ctx, updatePipelineRunScope,
		arg.ScopeStartedAt,
		arg.ScopeCompletedAt,
		arg.ScopeTokensIn,
		arg.ScopeTokensOut,
		arg.ScopeModel,
		arg.ScopeFilesSuggested,
		arg.ScopeEstimatedComplexity,
		arg.ScopeRagDirect,
		arg.ScopeRagHops,
		arg.ScopePathsStripped,
		arg.ScopePathsReclassified,
		arg.WorkflowID,
	)
	return err
}

const updatePipelineRunVerify = `-- name: UpdatePipelineRunVerify :exec
UPDATE pipeline_runs
SET verify_started_at = ?, verify_completed_at = ?,
    verify_tokens_in = ?, verify_tokens_out = ?,
    verify_model = ?, verify_result = ?,
    build_scope_drift = ?,
    updated_at = datetime('now')
WHERE workflow_id = ?
`

type UpdatePipelineRunVerifyParams struct {
	VerifyStartedAt   sql.NullString `json:"verify_started_at"`
	VerifyCompletedAt sql.NullString `json:"verify_completed_at"`
	VerifyTokensIn    sql.NullInt64  `json:"verify_tokens_in"`
	VerifyTokensOut   sql.NullInt64  `json:"verify_tokens_out"`
	VerifyModel       sql.NullString `json:"verify_model"`
	VerifyResult      sql.NullString `json:"verify_result"`
	BuildScopeDrift   int64          `json:"build_scope_drift"`
	WorkflowID        string         `json:"workflow_id"`
}

func (q *Queries) UpdatePipelineRunVerify(ctx context.Context, arg UpdatePipelineRunVerifyParams) error {
	_, err := q.db.ExecContext(ctx, updatePipelineRunVerify,
		arg.VerifyStartedAt,
		arg.VerifyCompletedAt,
		arg.VerifyTokensIn,
		arg.VerifyTokensOut,
		arg.VerifyModel,
		arg.VerifyResult,
		arg.BuildScopeDrift,
		arg.WorkflowID,
	)
	return err
}

const updatePipelineRunWorkOrderContent = `-- name: UpdatePipelineRunWorkOrderContent :exec
UPDATE pipeline_runs
SET work_order_content = ?, updated_at = datetime('now')
WHERE workflow_id = ?
`

type UpdatePipelineRunWorkOrderContentParams struct {
	WorkOrderContent sql.NullString `json:"work_order_content"`
	WorkflowID       string         `json:"workflow_id"`
}

func (q *Queries) UpdatePipelineRunWorkOrderContent(ctx context.Context, arg UpdatePipelineRunWorkOrderContentParams) error {
	_, err := q.db.ExecContext(ctx, updatePipelineRunWorkOrderContent, arg.WorkOrderContent, arg.WorkflowID)
	return err
}

const updateWorkflowBudget = `-- name: UpdateWorkflowBudget :exec
UPDATE workflows
SET current_depth = ?, files_changed = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateWorkflowBudgetParams struct {
	CurrentDepth int64  `json:"current_depth"`
	FilesChanged int64  `json:"files_changed"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateWorkflowBudget(ctx context.Context, arg UpdateWorkflowBudgetParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowBudget, arg.CurrentDepth, arg.FilesChanged, arg.ID)
	return err
}

const updateWorkflowContext = `-- name: UpdateWorkflowContext :exec
UPDATE workflows
SET context_package_path = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateWorkflowContextParams struct {
	ContextPackagePath sql.NullString `json:"context_package_path"`
	ID                 string         `json:"id"`
}

func (q *Queries) UpdateWorkflowContext(ctx context.Context, arg UpdateWorkflowContextParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowContext, arg.ContextPackagePath, arg.ID)
	return err
}

const updateWorkflowState = `-- name: UpdateWorkflowState :exec
UPDATE workflows
SET current_state = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateWorkflowStateParams struct {
	CurrentState string `json:"current_state"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateWorkflowState(ctx context.Context, arg UpdateWorkflowStateParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowState, arg.CurrentState, arg.ID)
	return err
}

const updateWorkflowVerification = `-- name: UpdateWorkflowVerification :exec
UPDATE workflows
SET verification_report_path = ?, current_state = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateWorkflowVerificationParams struct {
	VerificationReportPath sql.NullString `json:"verification_report_path"`
	CurrentState           string         `json:"current_state"`
	ID                     string         `json:"id"`
}

func (q *Queries) UpdateWorkflowVerification(ctx context.Context, arg UpdateWorkflowVerificationParams) error {
	_, err := q.db.ExecContext(ctx, updateWorkflowVerification, arg.VerificationReportPath, arg.CurrentState, arg.ID)
	return err
}
