// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	ClaimTask(ctx context.Context, arg ClaimTaskParams) (int64, error)
	CompleteTask(ctx context.Context, arg CompleteTaskParams) error
	CountSuccessfulApprovedRunsByPlanTaskID(ctx context.Context, arg CountSuccessfulApprovedRunsByPlanTaskIDParams) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) error
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) error
	FailTask(ctx context.Context, arg FailTaskParams) error
	GetPendingTask(ctx context.Context) (string, error)
	GetPipelineRunByWorkflowID(ctx context.Context, workflowID string) (GetPipelineRunByWorkflowIDRow, error)
	GetPipelineRunIDByWorkflowID(ctx context.Context, workflowID string) (string, error)
	GetPipelineStats(ctx context.Context) (GetPipelineStatsRow, error)
	GetPlanRunByID(ctx context.Context, id string) (GetPlanRunByIDRow, error)
	GetRecentPipelineRuns(ctx context.Context) ([]GetRecentPipelineRunsRow, error)
	GetScopeQualityStats(ctx context.Context) (GetScopeQualityStatsRow, error)
	GetStatsByWorkOrderType(ctx context.Context) ([]GetStatsByWorkOrderTypeRow, error)
	GetSubCallAggregatesByProvider(ctx context.Context, pipelineRunID string) ([]GetSubCallAggregatesByProviderRow, error)
	GetSubCallGlobalStatsByProvider(ctx context.Context) ([]GetSubCallGlobalStatsByProviderRow, error)
	GetSubCallPhaseAverages(ctx context.Context) ([]GetSubCallPhaseAveragesRow, error)
	GetSubCallsByPipelineRun(ctx context.Context, pipelineRunID string) ([]SubCall, error)
	GetTask(ctx context.Context, id string) (Task, error)
	GetVerifyHumanAgreement(ctx context.Context) ([]GetVerifyHumanAgreementRow, error)
	GetWorkflow(ctx context.Context, id string) (Workflow, error)
	InsertPlanRun(ctx context.Context, arg InsertPlanRunParams) error
	InsertSubCall(ctx context.Context, arg InsertSubCallParams) error
	ListEvents(ctx context.Context, workflowID sql.NullString) ([]Event, error)
	ListEventsSince(ctx context.Context, arg ListEventsSinceParams) ([]Event, error)
	ListLatestPipelineRunsByPlanFile(ctx context.Context, planFile sql.NullString) ([]ListLatestPipelineRunsByPlanFileRow, error)
	ReleaseTask(ctx context.Context, id string) error
	RetryTask(ctx context.Context, id string) error
	UpdatePipelineRunBuild(ctx context.Context, arg UpdatePipelineRunBuildParams) error
	UpdatePipelineRunHumanResult(ctx context.Context, arg UpdatePipelineRunHumanResultParams) error
	UpdatePipelineRunScope(ctx context.Context, arg UpdatePipelineRunScopeParams) error
	UpdatePipelineRunVerify(ctx context.Context, arg UpdatePipelineRunVerifyParams) error
	UpdatePipelineRunWorkOrderContent(ctx context.Context, arg UpdatePipelineRunWorkOrderContentParams) error
	UpdatePlanRunState(ctx context.Context, arg UpdatePlanRunStateParams) error
	UpdateWorkflowBudget(ctx context.Context, arg UpdateWorkflowBudgetParams) error
	UpdateWorkflowContext(ctx context.Context, arg UpdateWorkflowContextParams) error
	UpdateWorkflowState(ctx context.Context, arg UpdateWorkflowStateParams) error
	UpdateWorkflowVerification(ctx context.Context, arg UpdateWorkflowVerificationParams) error
}

var _ Querier = (*Queries)(nil)
